### ISSUE TITLE
deform_conv_cuda ImportError

### ISSUE THREAD

**Issue by KurochkinVasiliy** [Media-Smart/SKU110K-DenseDet#5]
installed by INSTALL.md  instructions, but getting error:

Traceback (most recent call last):
  File "tmp.py", line 2, in <module>
    from mmdet.apis import init_detector, inference_detector, show_result_pyplot
  File "/home/qra/projects/densedet/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/qra/projects/densedet/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/qra/projects/densedet/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/qra/projects/densedet/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/qra/projects/densedet/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/qra/projects/densedet/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/qra/projects/densedet/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/qra/projects/densedet/mmdet/ops/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'mmdet.ops.dcn' (most likely due to a circular                                                      import) (/home/qra/projects/densedet/mmdet/ops/dcn/__init__.py)

Help me to correct it, please

**Comment by mileistone** [comment]
there is no tmp.py in this repo, where is your tmp.py from?

**Comment by KurochkinVasiliy** [comment]
tmp.py is just a copy/paste from demo/inference_demo.ipynb 
full code:
```
from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv
config_file = '../SKU_fusion_bifpn_x50_64x4d_soft.py'
# download the checkpoint from model zoo and put it in `checkpoints/`
checkpoint_file = '../work_dirs/SKU_fusion_bifpn_x50_resume/epoch_10.pth'
# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')
# test a single image
img = 'demo.jpg'
result = inference_detector(model, img)
# show the results
show_result_pyplot(img, result, model.CLASSES)
```

**Comment by KurochkinVasiliy** [comment]
If i run demo/inference_demo.ipynb in jupyter lab i  get  this error
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a69dba14fb39> in <module>
----> 1 from ..mmdet.apis import init_detector, inference_detector, show_result_pyplot
      2 import mmcv

ImportError: attempted relative import with no known parent package
```

**Comment by mileistone** [comment]
> If i run demo/inference_demo.ipynb in jupyter lab i get this error
> 
> ```
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-a69dba14fb39> in <module>
> ----> 1 from ..mmdet.apis import init_detector, inference_detector, show_result_pyplot
>       2 import mmcv
> 
> ImportError: attempted relative import with no known parent package
> ```

You should install this repo, not mmdetection.

**Comment by edaayan-a** [comment]
I get the same error, I copied and pasted the contents of demo/inference_demo.ipynb to deneme.py. 

Traceback (most recent call last):
  File "deneme.py", line 2, in <module>
    from mmdet.apis import init_detector, inference_detector, show_result_pyplot
  File "/home/ubuntu/SKU110K-DenseDet/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/ubuntu/SKU110K-DenseDet/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/ubuntu/SKU110K-DenseDet/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/ubuntu/SKU110K-DenseDet/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/ubuntu/SKU110K-DenseDet/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/ubuntu/SKU110K-DenseDet/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/ubuntu/SKU110K-DenseDet/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/ubuntu/SKU110K-DenseDet/mmdet/ops/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from partially initialized module 'mmdet.ops.dcn' (most likely due to a circular import) (/home/ubuntu/SKU110K-DenseDet/mmdet/ops/dcn/__init__.py)

What might be the reason?
